version: "3.8"

services:
  service:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    image: github.com/pegondo/starwars-service:latest
    environment:
      - SWAPI_BASE_URL=${SWAPI_BASE_URL}
    ports:
      - "8080:8080"
